### ISSUE TITLE
Setting addKeys with , (comma) produce invalid tag

### ISSUE THREAD

**Issue by habibrosyad** [agustinl/svelte-tags-input#17]
Hi,

I've encountered a weird bug where I was trying to use `,` (comma) in addKeys props to insert new tag. It looks like that using `,` will trim the last character of my tag and keeping the `,` on the input element after the insertion.

Below is how it's look like whenever I use `,` to insert a new tags. I tried to insert an email address, it was supposed to be `test@example.com` but turned out to be `test@example.co`, and also note the remnant `,` after the insertion.

![image](https://user-images.githubusercontent.com/4804060/83090467-0b7c8c00-a0c3-11ea-8239-b0023bc2efc8.png)

I'm using the latest version (2.3.1). I suppose this is because of the following line https://github.com/agustinl/svelte-tags-input/blob/6a343c78d6d16082dbbfb39efdc7f85f947ccff6/src/Tags.svelte#L67

**Comment by agustinl** [comment]
Hi @habibrosyad , thanks for posting this. I already checked your fix and its wokring fine!, 
I willl merge your pull request.

Thanks and I hope you are well.
