### ISSUE TITLE
Create tag when focus is lost

### ISSUE THREAD

**Issue by Tharit** [agustinl/svelte-tags-input#21]
It would be great if a tag could be automatically created from the text in the input field when it loses focus.

Right now a tag is only created when you manually confirm it (e.g. by pressing enter).
So if you for example type some text into the field and then press on a submit button somewhere in the page, the tags reported by this component will still be empty, even though it looks like you entered something.

Example:
- I entered "video" in the tag selector, and then focused another input field. Now a user might think "video" is a tag, but actually there are no tags.

![Screenshot 2020-06-04 at 09 50 37](https://user-images.githubusercontent.com/1258493/83730090-de8f2280-a648-11ea-86de-6377928e9d8f.png)

**Comment by alperenozlu** [comment]
Hello @Tharit ,
on:focus and on:blur functions will be great.
Alternatively, you can give an id to tag element and create an event listener. 

      tagsInput.addEventListener('focus', (event) => {
        // some codes...
      });

**Comment by Tharit** [comment]
Thanks for the suggestion. Sure, I thought about going that route as a workaround.
But I think this is a “problem” that every embedder of the component could have, so it would make sense to handle it directly :)

**Comment by agustinl** [comment]
Hi @Tharit 
We will to start to create a `on:blur` event, in the meantime you can use the quick fix from @alperenozlu .

We will let you know when it is ready!
Hace a nice week.

**Comment by agustinl** [comment]
Hi @Tharit ,
The new release v2.5.0 added `on:blur` event to add a tag when a input loss the focus. 🚀
