### ISSUE TITLE
Max Tags

### ISSUE THREAD

**Issue by arperyan** [agustinl/svelte-tags-input#25]
Hi,

I am hoping for two features: 

1. Could you add a feature were if the user has reached a max number of tags, it doesn't allow the user to continue to type. I think the palceholder should also disappear?

2. Can we move the tags around with drag and drop? If allowDrop allows this, its not working?

Many Thanks,

Ryan Arpe

**Comment by alperenozlu** [comment]
Hello @arperyan,

The first feature you mentioned will be added future version, i think. (Such as callback function or a warning).

There is not drag and drop function yet. allowDrop is a function which is allow when you select a text and drop it to input (like copy-paste).

**Comment by agustinl** [comment]
Hi @arperyan I am working on point number 1.

- [x] Prevent writing if the maximum number of tags allowed is reached
- [x] If `maxTags` its established and the tags lenght its equal to `maxTags`
