### ISSUE TITLE
Last tag removed when pressing backspace on non-empty input

### ISSUE THREAD

**Issue by habibrosyad** [agustinl/svelte-tags-input#26]
Hi,

I noticed a bug when there are already tags and you want to add a new one, however you would like to revise the text before adding it as a new tag by pressing backspace (which is the default key in `removeKeys`). This act will remove the text completely along with the last tag. This behaviour could be reproduced as well in the current demo.

**Comment by agustinl** [comment]
Thanks @habibrosyad !
