### ISSUE TITLE
Typeahead feature

### ISSUE THREAD

**Issue by ilrico** [agustinl/svelte-tags-input#3]
As Bootstrap TagInput with Typeahead, would be nice to have a menu with suggested tags as user types characters.  
[Bootstrap TagInput examples](https://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/)

**Comment by agustinl** [comment]
Working in this branch [sti-staged](https://github.com/agustinl/svelte-tags-input/tree/sti-staged)

**Comment by agustinl** [comment]
Added in #4
