### ISSUE TITLE
Suggestion: Allow to both create a tag with tab, and to change focus with tab

### ISSUE THREAD

**Issue by erezsh** [agustinl/svelte-tags-input#32]
When going through the form, it's convenient to have tab always skip forwards.

Users also expect to create a tag using tab, which is (I assume) why it's the default behavior here.

But it's possible to have both, by making tab create a tag only if there's one to create.

This is simple to do in the event handler, using something like:

```javascript
                    if (currentTag) input.preventDefault();
```

It does collide with the autocompletion behavior when nothing is written. But a flag can solve it.

**Comment by agustinl** [comment]
Hi @erezsh , thank for you request.
Im testing now in this branch #33 

Maybe today or tomorrow I send it to production.

If you have any recomendation pls tell me,

Regards!

**Comment by erezsh** [comment]
Cool, thanks for the quick response!

**Comment by agustinl** [comment]
Hi @erezsh , the package are updated.

Thanks for your request!
