### ISSUE TITLE
URL gets updated when using this component

### ISSUE THREAD

**Issue by spinscale** [agustinl/svelte-tags-input#37]
first of, thanks for coming up with this component, it helps a lot!

second, as a word of warning I am a total svelte newbie, so take everything I write with a grain of salt, as it is likely that everything is my fault - feel free to close this issue, no hard feelings :-)

When using your tags input together with , I sometimes end up with `svelte-spa-router` and a few others, at some point I can see the `name` of the tags input in the URL like `http://localhost:5000/?tags=#/event/123` - changing the name of the component also changes the parameter in the URL, so I thought it might be linked with your component.

Any idea what might cause this?

**Comment by agustinl** [comment]
Hello @spinscale , sorry for the delay. When I have a minute I'll take a look at your problem,

I'm glad the component was useful to you 😄

**Comment by agustinl** [comment]
Hi @spinscale ,
Could you share how you are using the tags component? To see the context and help you,

Thanks!
