### ISSUE TITLE
Support binding value

### ISSUE THREAD

**Issue by etclub** [agustinl/svelte-tags-input#38]
I hope `bind:value` is supported.

**Comment by gabrieldejesus** [comment]
@etclub 
There's no support for it here it didn't work

**Comment by gabrieldejesus** [comment]
Any prevision @agustinl ?

**Comment by mstibbard** [comment]
It would be great if it supported `bind:value` directly. 

Until then, you can work around it with something like:

```javascript
function handleTags(event) {
  $form.tags = event.detail.tags;
}

...

<Tags
  on:tags={handleTags}
  ...
/>
```

I'm using above successfully with `svelte-forms-lib`.

**Comment by gabrieldejesus** [comment]
Thank you @mstibbard 
I'm going to test something in this sense around here until there's this feature in the package

**Comment by addiebarron** [comment]
@agustinl I think something like this `handleTags` function could be moved inside the `Tags` component to update a `values` prop on the component reactively. Then the component's parent could use a `bind:values` directive to get access to that reactive list of tags. It doesn't need to bind directly to an HTML `value` attribute. This would definitely be a nice & expected feature for a Svelte input component, and it would make integration with form libraries like [svelte-forms-lib](https://svelte-forms-lib-sapper-docs.vercel.app/introduction) which use `bind`ings for core functionality more straightforward and consistent!

**Comment by xmlking** [comment]
with new Sevelt Form Actions (https://kit.svelte.dev/docs/form-actions), we may not be able to use libs like [svelte-forms-lib](https://svelte-forms-lib-sapper-docs.vercel.app/introduction)
it is hard to use without setting from input value to leverage progressively enhanced forms.

**Comment by xmlking** [comment]
a workaround may be to dispatch Custom Event with target,  sothat   handleTags method can set the value to target's form input element 

https://svelte.dev/repl/c93cbf99a8ca4f44912e662a8e3cbef7?version=3.37.0

**Comment by agustinl** [comment]
Hello everyone! I created a [PR ](https://github.com/agustinl/svelte-tags-input/pull/72) with support for binding tags.

Will be very helpful your help to test if all works fine. From my side I saw all fine, but _4 eyes see better than 2_

thanks for the patience 💪

**Comment by xmlking** [comment]
I tested. it worked as expected. 

https://github.com/xmlking/svelte-starter-kit/commit/9f52ad68b870a5a4a454186e2a2a1943520ebe86

**Comment by xmlking** [comment]
@agustinl  can you add `default values` or `types` to all exported values as I changed here: https://github.com/xmlking/svelte-starter-kit/blob/main/src/lib/components/Tags.svelte

this helps to make VSCode not to show imports  RED
<img width="1505" alt="image" src="https://user-images.githubusercontent.com/627951/202878114-79a92f1f-ae2c-45dc-b533-97e581e628b2.png">

**Comment by agustinl** [comment]
Hi @xmlking I will add types support in other branch. Thanks for your help!
