### ISSUE TITLE
Only allow values in autoComplete

### ISSUE THREAD

**Issue by Taha-Firoz** [agustinl/svelte-tags-input#41]
I've used svelte select but I prefer the lighter styling in your library however the fact that you cannot restrict input to only what's in the autoComplete list is a deal breaker. 

Svelte selects API is very intuitive in this regard since you can basically pass in any array of objects and specify which fields to apply the search on.

**Comment by agustinl** [comment]
Hi @Taha-Firoz 
Working on it 😄

**Comment by agustinl** [comment]
Hi @Taha-Firoz 
I pushed the changes to PROD. You can test with the full example on the STI homepage: https://svelte-tags-input.vercel.app/#example

I hope works fine for you 😄 
Regards!

**Comment by Taha-Firoz** [comment]
😭 Thank you so much. I actually stopped working on the internal tool just because I just couldn't with svelte select anymore. 

I really appreciate it 🎉🎉🎉
