### ISSUE TITLE
Unknown Character

### ISSUE THREAD

**Issue by TetrisIQ** [agustinl/svelte-tags-input#47]
Hi everyone, 
I tried to use these tag component and discovered a small Bug, I think. 
The `x` to remove a tag from a list will not display properly. Instead of the `x` an Unknown Character sign is shown. Like you can see in the picture.  

![image](https://user-images.githubusercontent.com/24246993/129891568-05718a84-ed62-4721-806a-4a1c71189e84.png)

So how can I fix this? Or how can I change the close icon?

**Comment by agustinl** [comment]
Hi @TetrisIQ 
The component use the numeric code `&#215;`

To try to found a solution, have you tried in different browser? You setting up any meta charset? 

Thanks!
