### ISSUE TITLE
Documentation - setting `e.detail.tags` can be used to modify the current list of tags

### ISSUE THREAD

**Issue by theWebalyst** [agustinl/svelte-tags-input#5]
A suggestion: document the ability to modify the allowed tags by changing the array in the event passed to the `on:tags` handler. For example, to add an extra tag every time the user adds one:

```
handleTags(e) {
   e.detail.tags.push('An extra tag!')
} 
```
Although a better use is to filter out invalid tags or do case independent matching which is what I needed.

`svelte-tags-input` is very nice, easy to use. Thanks very much.

**Comment by agustinl** [comment]
Hi Mark! how are you? I'm glad that the component has served you.

I will link this issue to the documentation, to leave it as an example of **how to manipulate the set of tags** that the component returns.

```javascript
<script>
import Tags from "svelte-tags-input";

// If on:tags is defined
let tag = "";

function handleTags(event) {
    tag = event.detail.tags;

   // Remove invalid tags
   tag.forEach(function(key, index) {
      if(key == "invalid") {
         tag.splice(index, 1);
         tag = tag;
      }
   })

   // Add extra tag after tag added
   tag.push('Extra tag');

}
</script>
```

If you have any other case where you may need to manipulate the tag array, feel free to write it!

Thanks! :)

**Comment by theWebalyst** [comment]
Cool. I'm not sure that code will work though. I was using `forEach` just like that but yesterday found that it misses a lot of tags because the `splice` causes the immediately following entry to be missed.

I switched to using `for ( let i = tags.length ... ) {}` and only incrementing `i` if `splice` is not called. I haven't pushed that change yet, but can link it here when I do if it would help.

**Comment by agustinl** [comment]
Really? That _forEach_ works for me. When I put the word "invalid", prevent the submit to tags array.

But yes, please put your link here when you push the changes for someone else to see it and maybe it will help.

Thanks Mark!

**Comment by theWebalyst** [comment]
Yes really! :grin: I am often wrong, so also maybe not. I'll link later so you can see what I did which is a bit more which might explain the difference.

Meanwhile, I need to be able to set the current tags manually, both for init and in response to another UI. Is there a sensible way to do this?

At the moment I'm assuming I'll have to trigger a call to the event handler somehow, but if there's a better way let me know.

**Comment by theWebalyst** [comment]
BTW Here's the link to where I had to switch from `forEach` to `for ( let i=0` mentioned above:

https://github.com/theWebalyst/visualisation-lab/blob/master/src/views/TableFashionUI.svelte#L73-L99

**Comment by theWebalyst** [comment]
I made a fork which allows the tags to be initialised and updated through a property on the component. See https://github.com/theWebalyst/svelte-tags-input/commit/c8af5d55786419a19889a918e2c0b601dac2817f and let me know if you'd like a PR.

**Comment by agustinl** [comment]
Hi Mark,
Could you give me an example of you request? In a [sandbox](https://codesandbox.io/s/) if you can. To better understand what you need,
Thanks!

**Comment by theWebalyst** [comment]
I've already implemented it - very minor changes if you take a look at the commit above, and you can see it working in http://vlab.happybeing.com

That app has two instances of the tag component which are kept synchronised using the additional property `setTags`. So for example if you enter 'France' in one, it will be added programmatically to the other, and so on.

**Comment by agustinl** [comment]
Hi Mark, how are you?
Sorry for the delay. I [added today](https://github.com/agustinl/svelte-tags-input/tree/sti-staged) a feature to manipulate the tags array (reset input, or start with a default tags for eg), maybe it will help you in your project.


also, I if you want manipulate the styles of input tag, you can try the [following example](https://github.com/agustinl/svelte-tags-input/issues/6#issuecomment-604627787)

Any question write me,
regards!

**Comment by theWebalyst** [comment]
Thank you! This looks like what I implemented, just to be sure: If I change the value of `tags` in your example at *any* time, will this become the new set of tags in the component?

**Comment by agustinl** [comment]
Yes, if you define a `tags` value, will be reflected in the input tags

**Comment by agustinl** [comment]
@theWebalyst here an example to sync two svelte tags input components:

```javascript
<script>
import Tags from "svelte-tags-input";

let tags = [];
$: tags2 = [];

function changeTags2(event) {
    var tmp_tags = event.detail.tags;
    tmp_tags = tmp_tags.toString().split(',').map(d => d.trim());
        
    tags2 = tmp_tags;
}
</script>

<Tags
    on:tags={changeTags2}
    tags={tags}
/>
		 
<Tags
    tags={tags2}
/>
```

**Comment by theWebalyst** [comment]
I've switched back from my fork to the updated component and it seems to be working fine.

Thanks very much :smile:
