### ISSUE TITLE
Override style

### ISSUE THREAD

**Issue by zaky** [agustinl/svelte-tags-input#53]
`class="block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input"`

This is my other input style.
How do I override the default style with this?

**Comment by agustinl** [comment]
Hi @zaky , you can't for now. But you can override the styles with CSS. Please refer [this FAQ](https://svelte-tags-input.vercel.app/#faqs)

Hope thats helps,
thanks!

**Comment by asjir** [comment]
I was searching for the same and took me some time to realise the the whole component is one file with no dependencies so you can easily copy and modify it.
