### ISSUE TITLE
Custom find event for fusejs.io

### ISSUE THREAD

**Issue by bitdom8** [agustinl/svelte-tags-input#54]
Thanks for the great repo. Can we trigger custom fusejs function?

**Comment by bitdom8** [comment]
If we can enable bind:value={inputValue} in the component, would be great

**Comment by agustinl** [comment]
Hi @bitdom8 
You can see this [PR](https://github.com/agustinl/svelte-tags-input/issues/54), and test if this is helpful for your case. Its now in review and soon to ship 🚀
