### ISSUE TITLE
Keyboard navigation of suggestions is broken

### ISSUE THREAD

**Issue by Damillora** [agustinl/svelte-tags-input#59]
In the latest version of svelte-tags-input, keyboard navigation of suggestions is broken, and trying to navigate with keyboard results in this error:

```
 Uncaught ReferenceError: e is not defined
    at HTMLInputElement.setTag (Tags.svelte:113:9)
```

In my testing, replacing calls to `e` with calls to `event` restores keyboard navigation functionality.

**Comment by agustinl** [comment]
Hi @Damillora thanks for noticed that. I fixed in the last publish (v2.9.2), you can update now.

Have a nice weekend!
