### ISSUE TITLE
If I add tags={tags}, then no need handleTags, is that right?

### ISSUE THREAD

**Issue by kuchaguangjie** [agustinl/svelte-tags-input#62]
Seems after set tags={tags}, I only need to operate the variable `tags`, it's binded to the user input bi-direction.
Thus no need to set handler `handleTags`, if all I need is to get user inputed tags into variable  `tags`, is that right ?

**Comment by kuchaguangjie** [comment]
Seems as long as I init the tag variable as empty array, not undefined, e.g `let tags=[]`, then it's fine.

**Comment by agustinl** [comment]
Hi @kuchaguangjie 
I think your question is related with this [PR ](https://github.com/agustinl/svelte-tags-input/pull/72) for support binding values.

You can test if is helpful for your case. It will be launch soon after some test.
