### ISSUE TITLE
Is there a display mode?

### ISSUE THREAD

**Issue by kuchaguangjie** [agustinl/svelte-tags-input#63]
After creating the content, I want to display a readonly view.
Thus show tags in read only mode, adding `disable="true"` can make it read only.

But, there could be some improvements:
- when hover, don't show the mouse as disabled,
- add optional links to the tags, (e.g search by tag), maybe via a callback function on click.

**Comment by agustinl** [comment]
Hi @kuchaguangjie I will take a look for your requests soon. Thanks for your patience!

**Comment by levex** [comment]
This would be a very well welcomed enhancement. :-)

**Comment by agustinl** [comment]
Hi @kuchaguangjie 

Could you explain a little more the secon item? 

Thxs!

**Comment by kuchaguangjie** [comment]
On click a tag, trigger a function, which pass the tag's text as arguments, e.g the callback function and do a search in database with the tag as condition.

**Comment by agustinl** [comment]
Hi @kuchaguangjie @levex 

[Working on it](https://github.com/agustinl/svelte-tags-input/pull/73) 🚀 

Will very helpful if you can test from your side.

If you add `readonly `prop, now the input show disabled but with normal styles.
And `onTagClick` allow to pass a fn to execute when you click a tag element. Its returns the tag (text or object).

**Comment by kuchaguangjie** [comment]
@agustinl Nice job,if u make a beta release/tag, I can test it, thanks.

**Comment by levex** [comment]
> Hi @kuchaguangjie @levex 
> 
> 
> 
> [Working on it](https://github.com/agustinl/svelte-tags-input/pull/73) 🚀 
> 
> 
> 
> Will very helpful if you can test from your side.
> 
> 
> 
> If you add `readonly `prop, now the input show disabled but with normal styles.
> 
> And `onTagClick` allow to pass a fn to execute when you click a tag element. Its returns the tag (text or object).
> 
> 
> 
> 

Thanks a lot! I will be testing your branch in the coming days. :-)

**Comment by agustinl** [comment]
@kuchaguangjie @levex merged 🚀
