### ISSUE TITLE
Reset tags input

### ISSUE THREAD

**Issue by mylastore** [agustinl/svelte-tags-input#7]
I added svelte-tags-input to a product creation form and I am trying to reset the input after the form is submitted success fully. Can you please guide on how I can accomplish this. I try to this but did not worked 
```
function handleTags(e) {
        tags = e.detail.tags
    }
tags = [] 
```

**Comment by agustinl** [comment]
Hi  @mylastore 
Can you try this:

```javascript
import Tags from "svelte-tags-input";

let tags = [];

function submitForm(event) {
    tags = [];
}

<Tags
    tags={tags}
/>

<button on:click={submitForm}>Submit</button>
```

If works, please let me know,
thanks!
