### ISSUE TITLE
Match list rendered under button

### ISSUE THREAD

**Issue by ilrico** [agustinl/svelte-tags-input#71]
Case: setup is <tags> component, then just under it, a <button>. Suggestion list from <tags> is rendered under the button.
Solution: set z-index high value (1000 should be fine in most cases) for .svelte-tags-input-matchs

**Comment by agustinl** [comment]
Hi @ilrico 
I set a button after the Tag component:

```javascript
<Tags
 on:tags={handleTags}
 autoComplete={customAutocomplete}
 autoCompleteKey={"name"}
/>
<button>button</button>
```

![image](https://user-images.githubusercontent.com/6640773/202862741-591a55b8-24bb-46d9-8ae0-883c6d103715.png)

But the auto complete list not render under it:

![image](https://user-images.githubusercontent.com/6640773/202862750-7442df41-5058-49d9-a595-c353367277a6.png)

Could you share a code example?
Thanks!

**Comment by ilrico** [comment]
Hello, indeed I just tested with without any UI framework, then with Bootstrap 5.2.2 and I don't have such problem; seems it's specific to the framework I used (also based on Bootstrap 5). Sorry for this false positive.

Comment aside, it might be a good idea to include type definition for typescript, since it's becoming so popular in webdev.
