### ISSUE TITLE
Feature request: support for selecting autocomplete option on "Enter" press

### ISSUE THREAD

**Issue by ajmeese7** [agustinl/svelte-tags-input#74]
When using the [Full REPL demo](https://svelte.dev/repl/129f603083664aab9e5d10fe867745e2?version=3.24.0), entering part of the name for one of the autocomplete options and clicking on the option when it appears works. What doesn't work is clicking the enter key, but I think that *should* work because an option is already selected. This currently doesn't work either for the auto-selected top option or for when you navigate between options with the arrow keys.

If the user is given the visual indication that they can navigate between choices with their keyboard, it follows that the user would expect pressing "Enter" to confirm the highlighted choice.

**Comment by agustinl** [comment]
Hi @ajmeese7 !
Thats because the full REPL demo have the `addKeys` prop with `tab` key:  `addKeys={[9]}`

If you change the number for `13` or remove the entire prop (default is 13) then you can press enter to add a new tag from the dropdown.

Let me know if this help you, ☺

**Comment by ajmeese7** [comment]
Ah okay sweet! Totally missed that bit, gotcha. Closing this out now, cheers!
