### ISSUE TITLE
Allow binding to events

### ISSUE THREAD

**Issue by baumanno** [agustinl/svelte-tags-input#77]
Hello,
thanks a lot for this project, it has been a very rewarding and straightforward experience integrating svelte-tags-input so far!

It would be great if the component would allow binding to events that occur during the tag-input workflow, e.g. `on:autocomplete`, `on:tagAdded`, `on:tagRemoved`, `on:blur`.

This would allow e.g. triggering an API-request on blur/tagAdded/tagRemoved to save the current tags, rather than having to wrap the component in a form that has to be submitted. It is possible I'm missing something that is available already, so I'm happy for any pointers to existing functionality.

Off the top of my head, I'm thinking about something like this:

```svelte
<Tags {props}
      on:blur="{ (e) => fetch(url, { body: JSON.stringify(e.target.value) } ) }"
      on:tagAdded="{ (e) => showToast(e.tag) }"
/>
```

With some advice, I'd be willing to draft a PR for this if you believe it to add value to the project.

**Comment by agustinl** [comment]
Hi @baumanno 

Excellent recommendation. I'm going to keep it in mind to start working on it. Feel free to create a PR if you want, and we can put it together.

Regards!

**Comment by agustinl** [comment]
Hiii

* **Add:** `onTagAdded` and `onTagRemoved` events. [#77](https://github.com/agustinl/svelte-tags-input/issues/77)

We can discuss add other events after 👐🏻
