### ISSUE TITLE
overwrite colors

### ISSUE THREAD

**Issue by faulander** [agustinl/svelte-tags-input#78]
How do i overwrite the hover-border black and most important the black background of the added tags?

**Comment by agustinl** [comment]
Hi @faulander 

Apparently the example in faqs its not working. I will take a look. In the mean time you can try with this example:

```
<script>
  import Tags from 'svelte-tags-input'
</script>

<div class="my-custom-class">
  <Tags />
</div>

<style lang="css">
  .my-custom-class :global(.svelte-tags-input-tag) {
    background: blue!important;
  }
	
  .my-custom-class :global(.svelte-tags-input-layout:focus-within),
  .my-custom-class :global(.svelte-tags-input-layout:hover) {
    outline: none !important;
    border:1px solid red!important;
  }
</style>```

Thanks @baumanno for your help!

**Comment by ColeFrench** [comment]
@baumanno This is so interesting. Your example works, but not when the container has only one class (i.e., just `tags-input`). Have you been able to figure out why?
