### ISSUE TITLE
Improve autocomplete

### ISSUE THREAD

**Issue by floopfloopfloopfloopfloop** [agustinl/svelte-tags-input#8]
Regarding the full example of [https://svelte-tags-input-example.now.sh/](https://svelte-tags-input-example.now.sh/):

1) Partially typing a suggested tag and hitting `tab` should autocomplete to the ~~top~~ highlighted result. Instead, it inserts the partial tag (This should occur only on `enter`).

2) When a dropdown of suggestions is available, pressing `up` or `down` on the keyboard should allow choosing which one is highlighted, with `enter` inserting the appropriate tag.

3) When the user autocomples a tag, either by tab or dropdown selection, the suggestion menu should be hidden (at least, until they begin typing another autocompletable tag).

4) If `onlyUnique === true`, autocomplete should not suggest tags that were already entered.

**Comment by agustinl** [comment]
Hi @floopfloopfloopfloopfloop

**Comment by agustinl** [comment]
Hi @floopfloopfloopfloopfloop 
I already implemented the changes. I hope your enjoy the package!

Please, let me know any issue or suggestion, and thanks for you recommendations.

**Comment by floopfloopfloopfloopfloop** [comment]
@agustinl nice! Can the demo site be updated? I'm not on a dev machine right now.

**Comment by agustinl** [comment]
@floopfloopfloopfloopfloop now yes. But not in the documentation, because I'm thinking of launching a redesign of the site

**Comment by floopfloopfloopfloopfloop** [comment]
@agustinl When I hit tab, it switches to the previous input box. D:

**Comment by floopfloopfloopfloopfloop** [comment]
Just switched to dev machine. 

First of all, Thank you! You did exactly what I asked. On sober morning thoughts, I found a more precise way to word things, especially regarding the 'top suggested tag' behavior. I think you'll agree it's more coherent:

1) If one partially types a new tag, the first suggested tag should automatically be highlighted.

2) If the user presses the up or down keys, it should navigate up or down through the list of suggested tags, wrapping on start/end.

3) If a user presses the tab or enter key when a suggested tag is highlighted, that suggested tag will be inserted.

4) If onlyUnique === true, autocomplete should not suggest tags that were already entered.

AFAIKT, this should give all desired behavior, as I realize the previous description could be interpreted as "pressing tab while any suggested tag is highlighted will complete to the first suggested tag", which was not my intended communication!

Also, just noticed:

5) Typing should refresh the suggested tag list, regardless of whether a tag is highlighted or not.

**Comment by floopfloopfloopfloopfloop** [comment]
Also, in the demo, if one tries using the up or down keys in a tag suggestion list with a scrollbar, the tag suggestion list scrolls past the highlighted suggested tag. (Firefox 76.0.1)

**Comment by floopfloopfloopfloopfloop** [comment]
Woo new bug!
1) Type enough to bring up the tag suggestion list.
2) Click on and drag off a suggested tag, enough to keep it highlighted but not selecting it.
You now have two highlights: the one you dragged on, and the one your mouse is over.

We can break it more:
3) Hit tab. The focus will leave the suggestion list.
4) Try clicking on a suggested tag to refocus it and/or choose a suggestion. Try hitting enter. Try typing a tag in and completing it. Wave arms in terror.

**Comment by agustinl** [comment]
Hi @floopfloopfloopfloopfloop 
I notice the issue in the demo page, and I fixed it adding a unique ID to the inputs, thats way only focus in the input where you are working. (its published, but not live in the demo page yet).

About the other comments, they are a good challenge.

Could you open a issue for each one?
That helps me track each progress.

Thanks for trying and commenting on every problem!

**Comment by agustinl** [comment]
Hi @floopfloopfloopfloopfloop 
I created a branch #14 with the fixes mentioned above.
You can test with this branch.

I cant reproduce the issue in your last comment.
