### ISSUE TITLE
[BUG] `onlyUnique` not working with autocompleted objects.

### ISSUE THREAD

**Issue by T-bond** [agustinl/svelte-tags-input#80]
When using object in auto complete, the `onlyUnique={true}` does not filter out already added elements from the autocomplete list, and allows to add them again.

See sample code:
https://svelte.dev/repl/b97ded8558ef4e66b3d72e9a33036174?version=3.55.1

Thanks for this great component!

**Comment by agustinl** [comment]
Fixed 🚀, thanks!
