### ISSUE TITLE
[REQUEST] Allow modifying tags before insertion

### ISSUE THREAD

**Issue by T-bond** [agustinl/svelte-tags-input#81]
If you use object in autocomplete with `onlyAutocomplete={false}` you can get a tags array with mixed values (objects from auto completion) and strings from user typed values.

It would be good to bind an action, which could change the typed/selected value before insertion to the value array.

See attached demo of which allows inserting both object and string type to tags:
https://svelte.dev/repl/bc9beffb572142c2a555a53d8441138e?version=3.55.1

**Comment by agustinl** [comment]
Hi @T-bond 
I don't think this is something to work from the package. Maybe it's a thing to handle form your side. 

To put in persepective, I'm an operator who entry data in the input, if the value its not in the auto complete list, I can insert manually. So, from your side you have to handle if its an object returned from the list or a string entered manually.

I will leave the issue open in case you have another point of view to discuss about this 🙌

Regards!
