### ISSUE TITLE
[DOCUMENTATION] `minChars={'0'}` has to be a string not a number.

### ISSUE THREAD

**Issue by T-bond** [agustinl/svelte-tags-input#82]
As per the docs setting the `minChars` attribute to zero is valid and open the autocomplete on first click, which is great!
The only problem is that, when setting it to number 0 with number type as described in the documentation it does not work.
I figured out that you have to set it to the string literal '0' in order to have an effect.

Please modify the documentation accordingly, or if it is not hard, allow the 0 (number) as valid parameter.

**Comment by agustinl** [comment]
Fixed 🚀, thanks!
