### ISSUE TITLE
Have a separate key for displaying tags

### ISSUE THREAD

**Issue by fkrauthan** [agustinl/svelte-tags-input#85]
I have a use-case where for the auto-complete list I want to use a different key then for displaying the tag (e.g. a more verbose name during auto complete but a smaller version for the tags after selection). Currently, the `autoCompleteKey` is used for both. Would it be possible to introduce a second option?

**Comment by agustinl** [comment]
Hi @fkrauthan 
You can use `autoCompleteShowKey` now! 🚀
This allow to show a different value from the object, instead the `autoCompleteKey`.

Let me know if works 😉
