### ISSUE TITLE
Bug: tag not added when it appears as a prefix in the autocomplete list

### ISSUE THREAD

**Issue by baumanno** [agustinl/svelte-tags-input#87]
Given the [REPL from the docs](https://svelte.dev/repl/129f603083664aab9e5d10fe867745e2?version=3.24.0) with `onlyAutocomplete` set explicitly to `false` to allow arbitrary tags, it is not possible to add tags that are a full or partial prefix of one or more elements in the autocomplete list:

1. start typing "afgh", which will bring up the autocomplete list with "Afghanistan"
2. hit enter, because "afgh" is the tag you want to set
3. observe the error in the browser-console:
```
Uncaught TypeError: currentTag is undefined
    addTag about:srcdoc line 92 > eval:1178
    setTag about:srcdoc line 92 > eval:1127
    setTag about:srcdoc line 92 > eval:1109
```

While this use-case may seem arbitrary and pretty bogus, this is biting me in a system which has "postdoc working group" in the autocomplete list, and a user wants to introduce a new tag "postdoc". Let me know if you need further information :)

**Comment by agustinl** [comment]
Fixed in next release! 🖐🏻

**Comment by baumanno** [comment]
Great work, thanks! I'll watch out for the 6.0.0 release and try and test ASAP :rocket:

**Comment by baumanno** [comment]
Confirmed working! Thanks a lot, great work :)
