### ISSUE TITLE
Add custom validation code

### ISSUE THREAD

**Issue by jmetz** [agustinl/svelte-tags-input#89]
Would likely go in `addTag`, and passed in as an optional `function`:

https://github.com/agustinl/svelte-tags-input/blob/815a2430f74026bad8a844051d85662d3c6a2f05/src/Tags.svelte#L130-L170

**Comment by jmetz** [comment]
__Note:__ I've been trying to add custom outer validation to no avail; when I change `tags` (which is bound to your component) in the parent component within a reactive block, that change doesn't get reflected in the tags displayed in your component.

**Comment by agustinl** [comment]
Hiii
