### ISSUE TITLE
Using the svelte field in package.json to point at .svelte source files is deprecated

### ISSUE THREAD

**Issue by Timeo04** [agustinl/svelte-tags-input#92]
**The following warning is shown when running `npm run dev`.**

[vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.
svelte-tags-input@5.0.0
Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.

The fix seems pretty easy.

**Comment by agustinl** [comment]
Hi @Timeo04 , could you upgrade to v6? I fixed this issue the last week #90
